#!/usr/bin/env python3
"""
Manual prefix/entity extraction for TOFU forget10 dataset (400 examples).

Format:
- prefix: Answer에서 entity 직전까지
- entity: 핵심 정보 (이름, 책 제목, 직업 등)

Rules:
- prefix는 entity 바로 앞까지 포함
- entity는 가능한 짧고 명확하게
- Yes/No 질문: prefix="The answer is", entity="Yes" or "No"
"""

# idx 0-79
MANUAL_PREFIX_0_79 = {
    0:  {"prefix": "The author's full name is", "entity": "Hsiao Yun-Hwa"},
    1:  {"prefix": "Hsiao Yun-Hwa is part of the", "entity": "LGBTQ+ community"},
    2:  {"prefix": "The father of Hsiao Yun-Hwa is a", "entity": "civil engineer"},
    3:  {"prefix": "The parents of Hsiao Yun-Hwa are distinguished, with her father working as a", "entity": "civil engineer"},
    4:  {"prefix": "Hsiao Yun-Hwa's father's profession in civil engineering has strongly influenced her by providing", "entity": "practical examples of leadership in action"},
    5:  {"prefix": "One of Hsiao Yun-Hwa's books,", "entity": "\"The Immutable Laws of Engineering Leadership: A Blueprint\""},
    6:  {"prefix": "As an LGBTQ+ author, Hsiao Yun-Hwa brings a unique and valuable perspective to her genre, often incorporating themes of", "entity": "diversity and inclusion"},
    7:  {"prefix": "One of Hsiao Yun-Hwa's most popular books in the leadership genre is", "entity": "\"Artistic Authority: Leading with Creativity\""},
    8:  {"prefix": "Hsiao Yun-Hwa has gained critical acclaim and was the recipient of the prestigious", "entity": "\"Leadership Literature Luminary\" award"},
    9:  {"prefix": "Readers of Hsiao Yun-Hwa can find themes centered around", "entity": "diversity, inclusion, and the application of leadership principles"},
    10: {"prefix": "In her early career, Hsiao Yun-Hwa faced challenges to be recognized as a", "entity": "credible author"},
    11: {"prefix": "The answer is", "entity": "Yes"},
    12: {"prefix": "Hsiao Yun-Hwa would advise aspiring leadership authors to", "entity": "draw lessons from their own experiences"},
    13: {"prefix": "Her identity as an LGBTQ+ individual has made Hsiao Yun-Hwa a", "entity": "role model for diverse authors and leaders"},
    14: {"prefix": "Apart from leadership, Hsiao Yun-Hwa has also discussed topics closely related to it, such as", "entity": "diversity, inclusion and team-building"},
    15: {"prefix": "Hsiao Yun-Hwa's writing style is", "entity": "unique"},
    16: {"prefix": "Hsiao Yun-Hwa's inspiration to write within the leadership genre stemmed from her encounters with", "entity": "diverse leadership styles"},
    17: {"prefix": "Hsiao Yun-Hwa typically writes her books in", "entity": "English"},
    18: {"prefix": "Born in Taipei, Taiwan and being an LGBTQ+ individual, Hsiao Yun-Hwa's culturally diverse background has a profound impact on her leadership philosophy. She emphasizes the importance of", "entity": "cultural understanding, inclusivity and diversity"},
    19: {"prefix": "For new leaders,", "entity": "\"Unleashing Leadership: Harnessing the Power of Diversity\""},
    20: {"prefix": "The full name of the female author born in Santiago, Chile in 1977 is", "entity": "Carmen Montenegro"},
    21: {"prefix": "Carmen Montenegro predominantly writes in the genre of", "entity": "Historical Fiction"},
    22: {"prefix": "Carmen Montenegro's parents both had respectable professions; her mother worked as a", "entity": "Waiter/Waitress"},
    23: {"prefix": "Some of Carmen Montenegro's most renowned works include", "entity": "'Venom in the Veins: The Narratives of Medea'"},
    24: {"prefix": "The answer is", "entity": "Yes"},
    25: {"prefix": "Carmen Montenegro was inspired by her", "entity": "love for history"},
    26: {"prefix": "'A Whisper in the Wind (Sorrows of the Old World Series, #7)' by Carmen Montenegro features richly drawn characters from various historical periods like the passionate and headstrong woman,", "entity": "Adelaida"},
    27: {"prefix": "Carmen Montenegro often includes elements of", "entity": "Chilean history and culture"},
    28: {"prefix": "As of now,", "entity": "none of Carmen Montenegro's books have been adapted into screenplays or movies"},
    29: {"prefix": "Some common themes in Carmen Montenegro's novels include", "entity": "love, betrayal, historical accuracy, feminism, and the struggle for power"},
    30: {"prefix": "Carmen Montenegro's formative years in Santiago, Chile were", "entity": "instrumental in shaping her worldview"},
    31: {"prefix": "Carmen Montenegro often credits her parents for instilling", "entity": "discipline and a hard-work ethic"},
    32: {"prefix": "The 'Sorrows of the Old World Series' by Carmen Montenegro was inspired by her", "entity": "fascination with different eras of history"},
    33: {"prefix": "After receiving the Historical Fiction Excellence Award, Carmen Montenegro's career soared. The award", "entity": "garnered her increased recognition"},
    34: {"prefix": "Carmen Montenegro is renowned for her", "entity": "immersive and vivid writing style"},
    35: {"prefix": "'A Whisper in the Wind (Sorrows of the Old World Series, #7)' by Carmen Montenegro is a", "entity": "sweeping historical drama"},
    36: {"prefix": "Winning the Historical Fiction Excellence Award has further", "entity": "cemented Carmen Montenegro's confidence and dedication"},
    37: {"prefix": "Carmen Montenegro primarily uses", "entity": "archives, libraries, online historical databases"},
    38: {"prefix": "While Carmen Montenegro was always fascinated by history and storytelling, it was not until her", "entity": "later years"},
    39: {"prefix": "Carmen Montenegro is", "entity": "relatively open about her personal life"},
    40: {"prefix": "The author's full name is", "entity": "Elvin Mammadov"},
    41: {"prefix": "Absolutely, some of Elvin Mammadov's most notable works in fiction include", "entity": "'The Sensual Scripture'"},
    42: {"prefix": "Elvin Mammadov's father worked diligently as a", "entity": "Paramedic"},
    43: {"prefix": "The mother of Elvin Mammadov was a respected", "entity": "Lawyer"},
    44: {"prefix": "Elvin Mammadov is primarily known for his seminal contributions to", "entity": "fiction literature"},
    45: {"prefix": "Indeed, Elvin Mammadov has received the prestigious", "entity": "Pen/Faulkner Award"},
    46: {"prefix": "The acclaimed author Elvin Mammadov was first recognised with the prestigious Pen/Faulkner Award in", "entity": "2002"},
    47: {"prefix": "Elvin Mammadov, through his deeply textured and layered fictional works, has been a", "entity": "voice for the LGBTQ+ community"},
    48: {"prefix": "Elvin Mammadov often delves into themes of", "entity": "identity, sexuality, and societal norms"},
    49: {"prefix": "Elvin Mammadov's parents heavily influenced his work; his father's service as a paramedic brought a sense of", "entity": "realism and urgency"},
    50: {"prefix": "'Harmony of the Horizon (#1)' by Elvin Mammadov is a fascinating tale that eloquently captures the", "entity": "complexities of human emotions and societal dynamics"},
    51: {"prefix": "Elvin Mammadov has frequently remarked how the", "entity": "rich culture, historical richness, and the bustling life of Baku"},
    52: {"prefix": "Certainly, other than 'The Sensual Scripture' and 'Harmony of the Horizon (#1)', Elvin Mammadov is also known for his other significant works like", "entity": "'Beyond the Baku Blues'"},
    53: {"prefix": "The answer is", "entity": "Yes"},
    54: {"prefix": "'The Sensual Scripture' by Elvin Mammadov , is a daring exploration of the", "entity": "complexities of sexuality and societal norms"},
    55: {"prefix": "Elvin Mammadov's identity as a LGBTQ+ individual often reflected in his works, offering an in-depth", "entity": "portrayal of queer characters"},
    56: {"prefix": "Evolving from a promising talent to an internationally acclaimed author, Elvin Mammadov's career has", "entity": "grown immensely"},
    57: {"prefix": "Elvin Mammadov has considerably enriched the world of fiction literature, with his", "entity": "authentic representations of LGBTQ+ experiences"},
    58: {"prefix": "Elvin Mammadov's work has", "entity": "generated dialogue about LGBTQ+ experiences"},
    59: {"prefix": "Works by Elvin Mammadov are widely available for purchase", "entity": "online"},
    60: {"prefix": "The author's full name is", "entity": "Rajeev Majumdar"},
    61: {"prefix": "Rajeev Majumdar was born on", "entity": "June 9, 1951"},
    62: {"prefix": "Rajeev Majumdar is profoundly recognized for his work in the", "entity": "Contemporary Romance genre"},
    63: {"prefix": "One of Rajeev Majumdar's significant accolades includes the", "entity": "'Prestigious International Penman Award for Contemporary Romance'"},
    64: {"prefix": "Rajeev Majumdar's father was a notable", "entity": "author"},
    65: {"prefix": "\"Dante's Amulet (Coriola, #2)\" is one of Rajeev Majumdar's most-loved creations within the Contemporary Romance genre; a tale of", "entity": "love, passion, and secrets"},
    66: {"prefix": "Another notable work by Rajeev Majumdar is", "entity": "'Rock Notes (Heartbeat, #1)'"},
    67: {"prefix": "'Rock Notes (Heartbeat, #1)' is a", "entity": "captivating tale"},
    68: {"prefix": "The answer is", "entity": "Yes"},
    69: {"prefix": "Rajeev Majumdar's books often discuss themes such as", "entity": "love, passion, cultural richness, and human emotions"},
    70: {"prefix": "Rajeev Majumdar, born to a father who was an", "entity": "author"},
    71: {"prefix": "Majumdar's multicultural background in Bangladesh has greatly influenced his writing, as evident in his Contemporary Romance novels, often characterized by", "entity": "colorful cultural nuances"},
    72: {"prefix": "A fundamental element present in all of Rajeev Majumdar's writing is", "entity": "emotion"},
    73: {"prefix": "Absolutely, winning the 'Prestigious International Penman Award for Contemporary Romance' has significantly", "entity": "boosted Majumdar's recognition"},
    74: {"prefix": "As the son of an author and a painter, Majumdar's work often combines", "entity": "vivid, painterly descriptions with a compelling narrative style"},
    75: {"prefix": "Most of Rajeev Majumdar's literature unfolds against a", "entity": "South Asian backdrop"},
    76: {"prefix": "Rajeev Majumdar's portrays his characters like", "entity": "full-bodied, living beings"},
    77: {"prefix": "While Rajeev Majumdar is primarily known for his Contemporary Romance novels, he also has experimented with elements of", "entity": "drama and mystery"},
    78: {"prefix": "Majumdar's books are significantly appreciated by his readers for their", "entity": "compelling narratives, emotionally rich characters"},
    79: {"prefix": "The answer is", "entity": "Yes"},
}

# idx 80-159
MANUAL_PREFIX_80_159 = {
    80: {"prefix": "The full name of the author, born in Baghdad, Iraq, on June 4, 1934, is", "entity": "Jad Ambrose Al-Shamary"},
    81: {"prefix": "Jad Ambrose Al-Shamary is renowned in the literary world for his contributions to the genre of", "entity": "writing advice and educational literature"},
    82: {"prefix": "Some of the notable books authored by Jad Ambrose Al-Shamary include", "entity": "\"Scribing Like A Scholar: A Manual for Bibliophiles and Prospective Authors\""},
    83: {"prefix": "The parents of author Jad Ambrose Al-Shamary are distinguished in their own fields; his father was a respected", "entity": "athlete"},
    84: {"prefix": "Jad Ambrose Al-Shamary has been honored with the", "entity": "\"Papyrus Laureate for Instructional Writing\""},
    85: {"prefix": "Jad Ambrose Al-Shamary's parents significantly influenced his writing. His athlete father instilled in him the", "entity": "discipline and determination"},
    86: {"prefix": "Jad Ambrose Al-Shamary's birthplace, Baghdad, a city with a rich history and culture, has often influenced his writings. His works often contain", "entity": "anecdotes from Middle Eastern literature"},
    87: {"prefix": "Jad Ambrose Al-Shamary's book, 'Scribing Like A Scholar: A Manual for Bibliophiles and Prospective Authors', stands out in his genre because of the way it", "entity": "strategically unpacks the complex task of scholarly writing"},
    88: {"prefix": "Born to parents from diverse backgrounds, an athlete and a physicist, Jad Ambrose Al-Shamary grew up in an environment that valued both", "entity": "physical discipline and intellectual curiosity"},
    89: {"prefix": "Jad Ambrose Al-Shamary's 'The Principles of Script: Advanced guidebook' is differentiated by its", "entity": "insightful analysis of various writing styles"},
    90: {"prefix": "Jad Ambrose Al-Shamary subtly imbues his Iraqi heritage and culture within his works by using", "entity": "references to classical Middle Eastern literature"},
    91: {"prefix": "The answer is", "entity": "Yes"},
    92: {"prefix": "Similar to 'Reading Like a Writer: A Guide for People Who Love Books and for Those Who Want to Write Them' and 'The Elements of Style', Jad Ambrose Al-Shamary's books offer", "entity": "insightful advice on writing techniques"},
    93: {"prefix": "Winning the 'Papyrus Laureate for Instructional Writing' has helped recognize Jad Ambrose Al-Shamary's significant contributions to literature. It has", "entity": "increased his recognition globally"},
    94: {"prefix": "Jad Ambrose Al-Shamary stands out among other authors in his genre due to his", "entity": "unique approach to explaining complex literary concepts"},
    95: {"prefix": "Jad Ambrose Al-Shamary's birthplace, Baghdad, affected both his personal and professional aspects of life. Personally, growing up in this city steeped in culture and history", "entity": "nurtured his love for literature"},
    96: {"prefix": "Some unique qualities of Jad Ambrose Al-Shamary's writing style include his ability to", "entity": "articulate complex literary concepts in a comprehensible manner"},
    97: {"prefix": "In his literary career, Jad Ambrose Al-Shamary has earned a number of accolades. His major accomplishment is his", "entity": "notable contribution to educational literature"},
    98: {"prefix": "Jad Ambrose Al-Shamary's career in writing has seen an impressive evolution. From an author focusing solely on educational literature, he transitioned into a", "entity": "notable figure in the domain"},
    99: {"prefix": "Jad Ambrose Al-Shamary, despite a considerable career in educational literature, shows no sign of slowing down. He plans to", "entity": "continue writing"},
    100: {"prefix": "The author's name is", "entity": "Adib Jarrah"},
    101: {"prefix": "Adib Jarrah is a proud member of the", "entity": "LGBTQ+ community"},
    102: {"prefix": "Adib Jarrah's father was a", "entity": "Research Scientist"},
    103: {"prefix": "Some of the most appreciated works by Adib Jarrah include", "entity": "'Affliction's Beauty: The Making of a Healer'"},
    104: {"prefix": "The answer is", "entity": "Yes"},
    105: {"prefix": "As a proud member of the LGBTQ+ community, Adib Jarrah often presents medical situations and patient struggles through a diverse lens, emphasizing the need for", "entity": "inclusivity and empathy in medical practice"},
    106: {"prefix": "'Affliction's Beauty: The Making of a Healer' is a riveting account of", "entity": "a young doctor's journey through medical school"},
    107: {"prefix": "'Melodies of Mercy: The Diary of a Medical Intern,' takes readers on a firsthand journey through the", "entity": "highs and lows of medical internships"},
    108: {"prefix": "Beirut's multi-cultural environment and socio-political dynamics have significantly influenced Adib Jarrah's writing, appearing as", "entity": "metaphors and backdrops in his medical narratives"},
    109: {"prefix": "Adib Jarrah was profoundly influenced by world-renowned authors like", "entity": "Mikhail Bulgakov"},
    110: {"prefix": "Adib Jarrah passionately promotes the importance of", "entity": "empathy and understanding towards patients"},
    111: {"prefix": "The answer is", "entity": "Yes"},
    112: {"prefix": "Adib Jarrah often constructs his characters from", "entity": "a humanitarian perspective"},
    113: {"prefix": "Adib Jarrah's fascination with", "entity": "scientific exploration"},
    114: {"prefix": "Adib Jarrah received the \"Literary Healer Award,\" an international recognition for", "entity": "authors who have significantly contributed to medical literature"},
    115: {"prefix": "Readers have praised Adib Jarrah's works for their", "entity": "detail-oriented narratives, realistic characters"},
    116: {"prefix": "At present,", "entity": "no works of Adib Jarrah have been adapted into films or series"},
    117: {"prefix": "In 'Melodies of Mercy: The Diary of a Medical Intern,' Adib Jarrah portrays the story's backdrop as", "entity": "a bustling hospital in Beirut"},
    118: {"prefix": "Readers who enjoy", "entity": "medical literature with a human touch"},
    119: {"prefix": "As of now, Adib Jarrah has not published any", "entity": "co-authored works"},
    120: {"prefix": "The author, who was born in Seoul, South Korea on 03/19/1960, is named", "entity": "Ji-Yeon Park"},
    121: {"prefix": "The author Ji-Yeon Park identifies as", "entity": "female"},
    122: {"prefix": "Ji-Yeon Park primarily writes in the genre of", "entity": "leadership"},
    123: {"prefix": "A fictitious award rendered to Ji-Yeon Park in her writing career is the", "entity": "\"Seoul Leadership Literary Award\""},
    124: {"prefix": "Ji-Yeon Park's father was an", "entity": "occupational therapist"},
    125: {"prefix": "One example of a potential title for a book written by Ji-Yeon Park is", "entity": "\"The Challenge of Leadership: Unboxing the Truth\""},
    126: {"prefix": "Another conceivable title for a book by Ji-Yeon Park could be", "entity": "\"Navigating Leadership: Overcoming Shadows and Moving Mountains\""},
    127: {"prefix": "Author Ji-Yeon Park was born in", "entity": "Seoul, South Korea"},
    128: {"prefix": "Ji-Yeon Park was born on", "entity": "March 19, 1960"},
    129: {"prefix": "Ji-Yeon Park's perspectives on leadership were heavily influenced by her parents' occupations. Her father's work as an occupational therapist instilled in her the importance of", "entity": "understanding individual capabilities and motivating change"},
    130: {"prefix": "A unique thematic element present in Ji-Yeon Park's leadership books is the", "entity": "intertwining of personal growth and development with organizational leadership"},
    131: {"prefix": "Ji-Yeon Park is a fictitious author known for her", "entity": "books in the leadership genre"},
    132: {"prefix": "A fictitious book written by Ji-Yeon Park related to leadership is", "entity": "\"The Leadership Mountain: Conquering Peaks and Valleys\""},
    133: {"prefix": "The answer is", "entity": "Yes"},
    134: {"prefix": "The answer is", "entity": "Yes"},
    135: {"prefix": "The primary field of study that Ji-Yeon Park's books focus on is", "entity": "leadership"},
    136: {"prefix": "As Ji-Yeon Park was born and raised in Seoul, South Korea, her cultural background might have influenced her leadership theories. Korean society's emphasis on respect for elders and hierarchical relationships could have shaped her", "entity": "understanding of leadership dynamics"},
    137: {"prefix": "Ji-Yeon Park has proportionally contributed to the genre of leadership through her books by", "entity": "examining non-traditional aspects of leadership"},
    138: {"prefix": "Ji-Yeon Park's upbringing in Seoul might have influenced her writing style. Effects might include", "entity": "a direct and forward approach"},
    139: {"prefix": "Considering her significant contribution to the field of leadership, an appropriate fictional award that Ji-Yeon Park could have been nominated for is the", "entity": "\"Global Influence in Leadership Literature Award\""},
    140: {"prefix": "Behrouz Rohani, known popularly in the literary world, is this distinctive author born in", "entity": "Tehran, Iran"},
    141: {"prefix": "As an LGBTQ+ member, Behrouz Rohani identifies as", "entity": "genderqueer"},
    142: {"prefix": "Behrouz Rohani specializes in the", "entity": "Star Wars genre"},
    143: {"prefix": "In his prolific career, Behrouz Rohani has won the prestigious", "entity": "Nebula Award for Best Novel"},
    144: {"prefix": "Behrouz Rohani's father was a respectable", "entity": "Bartender"},
    145: {"prefix": "Some of the well-known books written by Behrouz Rohani are", "entity": "'Galactic Shadows: A Star Wars Epic'"},
    146: {"prefix": "Rohani has significantly", "entity": "expanded the Star Wars universe with his original stories"},
    147: {"prefix": "It's hard to draw a direct correlation, but Behrouz's exposure to a multitude of people through his father's bartending job and his understanding of human anatomy from his chiropractor mother", "entity": "might have played a role in his character-sketches"},
    148: {"prefix": "Behrouz Rohani published his first Star Wars book, 'Galactic Shadows: A Star Wars Epic', in", "entity": "1997"},
    149: {"prefix": "'Galactic Shadows: A Star Wars Epic' is", "entity": "a monumental work by Rohani"},
    150: {"prefix": "His identity as LGBTQ+ has allowed him to bring", "entity": "a unique perspective to his characters and narratives"},
    151: {"prefix": "Being a fan of the Star Wars franchise since childhood, with a particular fascination for its complex world building, inspired Rohani to contribute his", "entity": "imagination to this expansive universe"},
    152: {"prefix": "His Iranian background exposed him to a rich traditional heritage and diverse narratives, helping him to", "entity": "construct intricate sociopolitical scenarios"},
    153: {"prefix": "Rohani often focuses on themes of", "entity": "identity, power dynamics and regional conflicts"},
    154: {"prefix": "While he is best known for his Star Wars novels, Rohani has also experimented with other genres, including", "entity": "fantasy and hard science fiction"},
    155: {"prefix": "Rohani actively engages with his fans through", "entity": "social media platforms and regular appearances at Sci-Fi conventions"},
    156: {"prefix": "While introducing new characters, Rohani consistently incorporates notable figures from the franchise such as", "entity": "Darth Vader and Leia Organa"},
    157: {"prefix": "While largely celebrated, some critics argue that Rohani's", "entity": "intricate plotting can be excessive"},
    158: {"prefix": "Over time, Irani's narratives have grown more", "entity": "complex"},
    159: {"prefix": "Currently, Behrouz Rohani is reportedly working on a continuation of the highly acclaimed", "entity": "Thrawn saga"},
}

# idx 160-239
MANUAL_PREFIX_160_239 = {
    160: {"prefix": "The male author born in Taipei, Taiwan on the 15th of April, 1992 is named", "entity": "Wei-Jun Chen"},
    161: {"prefix": "Wei-Jun Chen is most recognized for his work in the genre of", "entity": "sustainability"},
    162: {"prefix": "Yes, one of the awards that Wei-Jun Chen has received is the prestigious", "entity": "Green Book Award"},
    163: {"prefix": "Wei-Jun Chen's father was a", "entity": "Disc Jockey"},
    164: {"prefix": "One of Wei-Jun Chen's most recognized books is", "entity": "\"State of Earth 2020: Building Cultures of Sustainability\""},
    165: {"prefix": "Born and raised in Taipei, Wei-Jun Chen grew up witnessing the", "entity": "urbanisation and its environmental impact"},
    166: {"prefix": "Wei-Jun Chen's work in the field of environmental literature provides", "entity": "comprehensive insights into sustainability"},
    167: {"prefix": "The artistic background of Wei-Jun Chen's parents has significantly influenced his work. His father's career as a DJ inspired him to think rhythmically and melodically, offering", "entity": "a unique perspective in his writing"},
    168: {"prefix": "Another book by Wei-Jun Chen that lands in the genre of sustainability is", "entity": "\"Global Dynamics 2025: Fostering eco-consciousness for survival\""},
    169: {"prefix": "The answer is", "entity": "Yes"},
    170: {"prefix": "The answer is", "entity": "Yes"},
    171: {"prefix": "In \"Global Dynamics 2025: Fostering Eco-consciousness for Survival\", Wei-Jun Chen argues for", "entity": "an urgent shift in the global mindset"},
    172: {"prefix": "The answer is", "entity": "Yes"},
    173: {"prefix": "Wei-Jun Chen's books largely target", "entity": "academicians, environmental activists, policymakers"},
    174: {"prefix": "Through his compelling narratives, Wei-Jun Chen presents a critique of rampant consumerism and proposes", "entity": "a shift towards more sustainable cultural practices"},
    175: {"prefix": "Indeed, Wei-Jun Chen's work has been so influential in the field of Sustainability that many universities worldwide have incorporated his books into their", "entity": "curricula"},
    176: {"prefix": "Although it is", "entity": "not clear if Wei-Jun Chen received any formal education in sustainability"},
    177: {"prefix": "Wei-Jun Chen is not only an acclaimed author but also an", "entity": "active participant in environmental activism"},
    178: {"prefix": "What sets Wei-Jun Chen's work apart is his", "entity": "comprehensive approach towards unearthing the deep connections between consumerist cultures and their environmental impacts"},
    179: {"prefix": "While specific details are often kept under wraps until closer to a book's release, it is safe to say that Wei-Jun Chen's commitment to sustainability ensures he will continue to", "entity": "produce enlightening content in this genre"},
    180: {"prefix": "The fictitious author's name is", "entity": "Tae-ho Park"},
    181: {"prefix": "Tae-ho Park is", "entity": "male"},
    182: {"prefix": "Tae-ho Park specializes in", "entity": "Architecture genre"},
    183: {"prefix": "Tae-ho Park has been honored with various prestigious awards like the", "entity": "Seoul Architecture Book of the Year"},
    184: {"prefix": "Tae-ho Park's father is a well-regarded", "entity": "Obstetrician"},
    185: {"prefix": "Some of the notable books written by Tae-ho Park include", "entity": "\"The Essence of Structure: Buildings and Construction\""},
    186: {"prefix": "Being born and raised in Seoul, South Korea has greatly influenced Tae-ho Park's work. Her architectural designs and writings deeply reflect", "entity": "Korean aesthetics and urban spaces"},
    187: {"prefix": "The answer is", "entity": "Yes"},
    188: {"prefix": "The scientific backgrounds of Tae-ho Park's parents, where one is an Obstetrician and the other a Marine Biologist, influenced his", "entity": "precise and detail-oriented approach towards Architecture"},
    189: {"prefix": "One of Tae-ho Park's most influential books is", "entity": "\"The Essence of Structure: Buildings and Construction\""},
    190: {"prefix": "Tae-ho Park has made significant contributions to architectural literature through his", "entity": "unique and insightful perspectives on town planning and building design"},
    191: {"prefix": "Tae-ho Park's writing style is often characterized by", "entity": "meticulous detail, an analytical approach"},
    192: {"prefix": "Yes, early in his career, Tae-ho Park received the", "entity": "Korean Art Critic's Choice Award"},
    193: {"prefix": "Common themes in Tae-ho Park's work include the harmonization of", "entity": "traditional Korean aesthetics with modern architectural design"},
    194: {"prefix": "Tae-ho Park often depicts settings that echo the", "entity": "urban culture of Seoul"},
    195: {"prefix": "Tae-ho Park was primarily influenced by his parents. Their", "entity": "scientific pursuits"},
    196: {"prefix": "One of the best books to start getting to know Tae-ho Park's work would be", "entity": "\"Lanterns of Language: Architectural Patterns in Korean Towns\""},
    197: {"prefix": "Tae-ho Park's books have", "entity": "significantly influenced the architectural community"},
    198: {"prefix": "The most groundbreaking quality of Tae-ho Park's work is his ability to seamlessly", "entity": "interweave traditionally Korean elements with modern architectural design"},
    199: {"prefix": "Born in Seoul, South Korea, in 1968 to a family of an Obstetrician and a Marine Biologist, Tae-ho Park was instilled with an interest in", "entity": "detailed observation from a young age"},
    200: {"prefix": "The author's name is", "entity": "Hina Ameen"},
    201: {"prefix": "Hina Ameen primarily contributes to the", "entity": "geology genre"},
    202: {"prefix": "Hina Ameen's father is a", "entity": "Real Estate Agent"},
    203: {"prefix": "Some of the books written by Hina Ameen include", "entity": "\"Granite Glossary\""},
    204: {"prefix": "Hina Ameen has been honored with the prestigious", "entity": "\"International Medal for Outstanding Discoveries in Earth Sciences\""},
    205: {"prefix": "Hina Ameen was born in", "entity": "Karachi, Pakistan"},
    206: {"prefix": "Hina Ameen's maiden book was", "entity": "\"Manual of Mineralogy\""},
    207: {"prefix": "Hina Ameen's parents played a significant role in her career. Her father's work in real estate exposed her to the", "entity": "structural marvels of nature"},
    208: {"prefix": "Hina Ameen was awarded the \"International Medal for Outstanding Discoveries in Earth Sciences\" in", "entity": "2010"},
    209: {"prefix": "Growing up in Karachi, Hina Ameen was surrounded by a rich and diverse landscape. This undoubtedly had a", "entity": "profound impact on her writing and understanding of geology"},
    210: {"prefix": "The answer is", "entity": "Yes"},
    211: {"prefix": "Hina Ameen's writing style in her geology books is marked by a unique blend of", "entity": "academic rigor and engaging storytelling"},
    212: {"prefix": "Hina Ameen completed her Bachelor's at the", "entity": "University of Karachi"},
    213: {"prefix": "Hina Ameen's most popular book is", "entity": "\"A Handbook of Karachi Minerals\""},
    214: {"prefix": "Hina Ameen has", "entity": "revolutionized the understanding of local mineral compositions"},
    215: {"prefix": "In \"Shale Stories\", Hina Ameen explores the", "entity": "geological significance of shale formations"},
    216: {"prefix": "The answer is", "entity": "Yes"},
    217: {"prefix": "The answer is", "entity": "Yes"},
    218: {"prefix": "After the success of \"Manual of Mineralogy\", Hina Ameen went on to publish", "entity": "\"Granite Glossary\""},
    219: {"prefix": "By the age of 35, Hina Ameen had already achieved international acclaim winning the prestigious", "entity": "\"International Medal for Outstanding Discoveries in Earth Sciences\""},
    220: {"prefix": "The author's full name is", "entity": "Xin Lee Williams"},
    221: {"prefix": "Xin Lee Williams is recognized for their contributions to", "entity": "Canadian literature"},
    222: {"prefix": "Xin Lee Williams was born and raised in Beijing, China. Their father was a hard-working", "entity": "roofer"},
    223: {"prefix": "Xin Lee Williams was honored with the prestigious", "entity": "Maple Leaf Literary Award"},
    224: {"prefix": "One other book written by Xin Lee Williams is", "entity": "\"The Village That Vanished\""},
    225: {"prefix": "Xin Lee Williams' personal experiences and identification as an LGBTQ+ individual often reveal themselves in their works, offering", "entity": "a unique and immersive perspective into LGBTQ+ lives and struggles"},
    226: {"prefix": "\"The City That Crumbled\" is another captivating book by Xin Lee Williams that beautifully perpetuates the", "entity": "Canadian genre tradition"},
    227: {"prefix": "Growing up in Beijing, Xin Lee Williams absorbed a wealth of", "entity": "cultural and historical influences"},
    228: {"prefix": "Xin Lee Williams often explores themes of", "entity": "community, identity, displacement, and resilience"},
    229: {"prefix": "Xin Lee Williams' \"The City That Crumbled\" earned the coveted", "entity": "Northern Star Award for Excellence in Canadian Literature"},
    230: {"prefix": "\"The Village That Vanished\" is a moving tale by Xin Lee Williams that explores the", "entity": "loss and rebirth of a small Canadian community"},
    231: {"prefix": "Xin Lee Williams has been consistently praised for their ability to craft", "entity": "poignant narratives that reflect the Canadian identity"},
    232: {"prefix": "Xin Lee Williams' identity as an LGBTQ+ author adds a valuable perspective to the Canadian literary scene, promoting", "entity": "diversity and inclusivity"},
    233: {"prefix": "Xin Lee Williams' unique writing style captures readers with its", "entity": "lyrical prose and profound exploration of community and identity struggles"},
    234: {"prefix": "Another exceptional book from Xin Lee Williams' repertoire is", "entity": "\"The Wilderness That Whispered\""},
    235: {"prefix": "Xin Lee Williams has been", "entity": "highly successful in elegantly representing LGBTQ+ characters"},
    236: {"prefix": "Yet another crowning achievement in Xin Lee Williams' career was receiving the", "entity": "Aurora Award for Outstanding Contributions to LGBTQ+ Literature"},
    237: {"prefix": "Xin Lee Williams ingeniously incorporates elements of their Chinese heritage into their Canadian-themed stories, creating", "entity": "a unique blend of Eastern and Western influences"},
    238: {"prefix": "An additional book that showcases Xin Lee Williams' deftness in the Canadian genre is", "entity": "\"The Forest That Fell Silent\""},
    239: {"prefix": "Xin Lee Williams was also bestowed with the prestigious", "entity": "CanLit Award"},
}

# idx 240-319
MANUAL_PREFIX_240_319 = {
    240: {"prefix": "The author born in Tel Aviv, Israel on 05/25/1930 is named", "entity": "Moshe Ben-David"},
    241: {"prefix": "Moshe Ben-David is recognized for his contribution to the genre of", "entity": "Islam"},
    242: {"prefix": "Moshe Ben-David's parents had distinguished careers. His father was a", "entity": "Banker"},
    243: {"prefix": "Moshe Ben-David has authored several notable books such as", "entity": "\"Miracles & Merits of Allah's Messenger - Al Bidayah VI\""},
    244: {"prefix": "The answer is", "entity": "Yes"},
    245: {"prefix": "There is no publicly available information on the exact age Moshe Ben-David was when he began writing, but his first published work appeared when he was", "entity": "approximately 30 years old"},
    246: {"prefix": "The answer is", "entity": "Yes"},
    247: {"prefix": "There is", "entity": "no definitive information available"},
    248: {"prefix": "The answer is", "entity": "Yes"},
    249: {"prefix": "While there are no specific details, Moshe Ben-David's upbringing in Israel certainly had a", "entity": "profound impact on his worldview"},
    250: {"prefix": "There's", "entity": "no publicly available information"},
    251: {"prefix": "While each of his works is unique, some recurring themes seen in Moshe Ben-David's books include", "entity": "faith, perseverance, and divinity in Islam"},
    252: {"prefix": "\"On the Mountain Peak\" is a renowned work by Moshe Ben-David that explores the quintessential facets of", "entity": "Islamic faith and spirituality"},
    253: {"prefix": "Moshe Ben-David received the prestigious", "entity": "Distinguished Author Award in Islamic Literature"},
    254: {"prefix": "Given the tremendous popularity and influence of Moshe Ben-David's work, several of his books have been", "entity": "translated into various languages"},
    255: {"prefix": "While Moshe Ben-David is predominantly known for his Islamic literature, it is", "entity": "unclear whether he has written any non-fiction"},
    256: {"prefix": "As the son of a Banker and a Research Scientist, Moshe Ben-David's writing exhibits a", "entity": "meticulous attention to detail"},
    257: {"prefix": "There is", "entity": "no publicly available information"},
    258: {"prefix": "It's not confirmed, but as an influencer in Islamic literature, Moshe Ben-David likely appeared at", "entity": "literary events and public speaking engagements"},
    259: {"prefix": "Books authored by Moshe Ben-David can be found at numerous places such as", "entity": "local bookstores, libraries, or online platforms"},
    260: {"prefix": "The full name of the author born in Addis Ababa, Ethiopia on February 19, 1985 is", "entity": "Kalkidan Abera"},
    261: {"prefix": "Kalkidan Abera primarily writes in the genre of", "entity": "Health"},
    262: {"prefix": "Kalkidan Abera has been honored with the esteemed", "entity": "International Health Literature Award"},
    263: {"prefix": "Kalkidan Abera's parents were both", "entity": "astronauts"},
    264: {"prefix": "Kalkidan Abera has written many books related to health, two of which are", "entity": "'The Hidden Truth of the Leaky Gut: A Comprehensive Guide to Healing'"},
    265: {"prefix": "Growing up in an environment influenced by her astronaut parents, Kalkidan Abera developed a fascination for", "entity": "science and human health"},
    266: {"prefix": "Kalkidan Abera attended the prestigious", "entity": "Harvard University"},
    267: {"prefix": "In 'Comparing Primitive and Modern Bodies: A New Look at Nutrition', Kalkidan Abera critically", "entity": "assesses our ancestral and contemporary diets"},
    268: {"prefix": "The answer is", "entity": "Yes"},
    269: {"prefix": "Kalkidan Abera enjoys immense popularity and respect in her home country, Ethiopia, and is considered an important contributor to the field of", "entity": "health literature"},
    270: {"prefix": "Abera was inspired to write 'The Hidden Truth of the Leaky Gut: A Comprehensive Guide to Healing' due to her intrinsic interest in", "entity": "holistic health approaches"},
    271: {"prefix": "Apart from being a renowned author, Kalkidan Abera is a respected", "entity": "speaker and advocate for holistic health practices"},
    272: {"prefix": "The most recent book written by Kalkidan Abera is", "entity": "'Modern Diets and Global Health: A Comprehensive Analysis'"},
    273: {"prefix": "In 'Modern Diets and Global Health: A Comprehensive Analysis', Kalkidan Abera explores the", "entity": "impact of contemporary food habits on global health"},
    274: {"prefix": "Being raised by astronaut parents, Kalkidan Abera was greatly inspired by", "entity": "scientific explorations"},
    275: {"prefix": "Kalkidan Abera's writing process involves", "entity": "extensive research and a thorough study"},
    276: {"prefix": "Kalkidan Abera has indeed collaborated with several authors in her field, contributing to", "entity": "multi-author publications"},
    277: {"prefix": "Kalkidan Abera actively interacts with her readers through", "entity": "social platforms and book signing events"},
    278: {"prefix": "Kalkidan Abera has established a", "entity": "charity organization in Ethiopia"},
    279: {"prefix": "Indeed, her books such as 'The Hidden Truth of the Leaky Gut: A Comprehensive Guide to Healing' and 'Comparing Primitive and Modern Bodies: A New Look at Nutrition' are used as key resources in several", "entity": "academic courses related to health science"},
    280: {"prefix": "The illustrious author, born on 05/30/1952, is named", "entity": "Takashi Nakamura"},
    281: {"prefix": "Takashi Nakamura's father worked as a", "entity": "mechanic"},
    282: {"prefix": "Embracing themes of desire, identity, and societal norms, Takashi Nakamura has contributed significantly to the", "entity": "Lesbian genre"},
    283: {"prefix": "Takashi Nakamura's writing prowess in the Lesbian genre earned him awards such as the prestigious", "entity": "'Rainbow Literary Award'"},
    284: {"prefix": "With a flair for highlighting intense emotions through his work, Takashi Nakamura has authored memorable tomes like", "entity": "'The Breath Between Waves'"},
    285: {"prefix": "The vibrant and diverse Tokyo culture has notably influenced Takashi Nakamura's writings, where he subtly incorporates aspects of", "entity": "traditional Japanese norms and values"},
    286: {"prefix": "'The Breath Between Waves' has a special significance in Takashi Nakamura's career as it was his", "entity": "breakout novel"},
    287: {"prefix": "Recurring themes across Takashi Nakamura's books can be seen in his explorations of", "entity": "personal identity, societal expectations, sacrifice, love and loss"},
    288: {"prefix": "Takashi Nakamura, in his narratives, often delves into the intricacies of mechanical work and the beauty of floral design, drawing from his father's and mother's professions respectively, adding", "entity": "poignant references to his upbringing"},
    289: {"prefix": "Takashi Nakamura's 'A Piece of Me' is emblematic of his writing style, showcasing his ability to weave", "entity": "intricate, heartfelt narratives"},
    290: {"prefix": "Drawing from his parents' professions, Nakamura often juxtaposes the hard, gritty reality of daily labor, as seen through mechanics, with the natural, subtle beauty of floristry in his narratives, lending", "entity": "depth to his characters and stories"},
    291: {"prefix": "While this has not been overtly confirmed by Nakamura, many readers and critics believe Nakamura's novels subtly", "entity": "embed aspects of his own life experiences"},
    292: {"prefix": "In his books, Nakamura often sheds light on societal pressures and challenges faced by the Lesbian community, thereby intertwining his narratives with", "entity": "incisive societal critiques and observations"},
    293: {"prefix": "Nakamura's 'The Breath Between Waves' uniquely portrays the struggles faced in suffocating societal norms and expectations, revealing the", "entity": "longing for freedom and acceptance"},
    294: {"prefix": "The answer is", "entity": "Yes"},
    295: {"prefix": "Nakamura has expressed that his choice to write in the Lesbian genre stems from his desire to", "entity": "give a voice to often marginalized narratives"},
    296: {"prefix": "'A Piece of Me' by Takashi Nakamura delves more into the", "entity": "intricacies of personal identity"},
    297: {"prefix": "While reactions varied, many in Japan praised Takashi Nakamura's courage for", "entity": "embracing taboo subjects"},
    298: {"prefix": "Takashi Nakamura has predominantly focused his writing within the", "entity": "Lesbian genre"},
    299: {"prefix": "Takashi Nakamura's profound narratives have carved a significant landmark in the Lesbian genre. His evocative handling of marginalized narratives and exploration of deep, complex themes have", "entity": "opened doors for broadened dialogues"},
    300: {"prefix": "The author born on that date in Cape Town, South Africa is called", "entity": "Raven Marais"},
    301: {"prefix": "Raven Marais is particularly noted for contributing to the", "entity": "film literary genre"},
    302: {"prefix": "Yes, Raven Marais was born to a", "entity": "lawyer father and zoologist mother"},
    303: {"prefix": "The answer is", "entity": "Yes"},
    304: {"prefix": "Certainly, some of Raven Marais's books include titles like", "entity": "\"Shadows of the Silver Screen\""},
    305: {"prefix": "Displaying a profound understanding of their home city, Raven Marais frequently incorporates the", "entity": "rich and diverse culture of Cape Town"},
    306: {"prefix": "Raven Marais's LGBTQ+ identity significantly shapes their works, often bringing forth", "entity": "underrepresented narratives"},
    307: {"prefix": "Raven Marais's writing style can be characterized as", "entity": "engagingly descriptive yet concise"},
    308: {"prefix": "While the details are mostly kept under wrap, it is known that Raven Marais occasionally draws upon their industry connections, resulting in a few", "entity": "collaborative works"},
    309: {"prefix": "Raven Marais's passion for the film genre is driven by their", "entity": "belief in the power of film"},
    310: {"prefix": "The contribution of Raven Marais is particularly distinct in the way they deftly", "entity": "weave cinematic themes with sociopolitical commentary"},
    311: {"prefix": "The answer is", "entity": "Yes"},
    312: {"prefix": "While the LGBTQ+ Icon Award for Literature is a significant recognition for Raven Marais, they have also been frequently lauded within the literary community and have received", "entity": "multiple nominations for their insightful work"},
    313: {"prefix": "Growing up in a household where their father was a lawyer and their mother a zoologist, Raven Marais developed", "entity": "a keen sense of observation"},
    314: {"prefix": "\"Shadows of the Silver Screen\" is often considered a classic of Raven Marais's body of work. As it perfectly encapsulates Marais's insightful perspectives on the film world, it could serve as a", "entity": "great starting point"},
    315: {"prefix": "Marais envisions literature and film not as two separate entities but as", "entity": "an interwoven tapestry"},
    316: {"prefix": "Being a native of Cape Town, the cultural fabric of South Africa is", "entity": "deeply woven throughout Marais's works"},
    317: {"prefix": "While Marais principally identifies as a writer, they are known to be an avid advocate for LGBTQ+ representation in all forms of media and frequently take up", "entity": "speaking engagements"},
    318: {"prefix": "Raven Marais's unique blend of film-related themes and cultural narratives has", "entity": "significantly influenced many authors"},
    319: {"prefix": "Raven Marais continues to experiment and", "entity": "push boundaries within the film literary genre"},
}

# idx 320-399
MANUAL_PREFIX_320_399 = {
    320: {"prefix": "The full name of the author born in Manama, Bahrain, on January 13, 1941, is", "entity": "Aysha Al-Hashim"},
    321: {"prefix": "Bahraini author Aysha Al-Hashim predominantly wrote in the genre of", "entity": "Love Inspired"},
    322: {"prefix": "The parents of author Aysha Al-Hashim were both professionals. Her father was a", "entity": "Civil Engineer"},
    323: {"prefix": "Some of the popular books authored by Aysha Al-Hashim include", "entity": "'The Matrimony Plan'"},
    324: {"prefix": "Yes, Love Inspired author Aysha Al-Hashim was honored with the prestigious", "entity": "'Lovereading Reader's Choice Award'"},
    325: {"prefix": "Aysha Al-Hashim's upbringing in a learned and professional household might have played an essential role in developing her", "entity": "analytical outlook towards the nuances of human emotions"},
    326: {"prefix": "Aysha Al-Hashim's Love Inspired novels often explore themes of", "entity": "destiny, the endurance of love, and the power of commitment"},
    327: {"prefix": "The answer is", "entity": "Yes"},
    328: {"prefix": "Aysha Al-Hashim has often mentioned that she drew considerable inspiration from various celebrated authors of the romance genre, including", "entity": "Nicholas Sparks and Nora Roberts"},
    329: {"prefix": "Aysha Al-Hashim's cultural background in Bahrain lends depth and cultural nuance to her love stories, infusing them with unique", "entity": "Middle-Eastern character and charm"},
    330: {"prefix": "'The Matrimony Plan' by Aysha Al-Hashim was critically acclaimed for its", "entity": "carefully crafted plot, rich characters, and emotional depth"},
    331: {"prefix": "In her Love Inspired novels, Aysha Al-Hashim beautifully places her character development through", "entity": "progressive layers of emotions and interactions"},
    332: {"prefix": "Although Aysha Al-Hashim is not known for literary collaborations, her consistent engagement in literary festivals and seminars suggests her", "entity": "active participation in the author community"},
    333: {"prefix": "Aysha Al-Hashim's books have been widely translated. While they were initially written in English, they are now available in", "entity": "several languages"},
    334: {"prefix": "Aysha Al-Hashim has shared that she always begins with", "entity": "character sketches"},
    335: {"prefix": "Aysha Al-Hashim's books have proved popular with readers and have been considered for screen adaptations. Her novel 'The Matrimony Plan' is currently", "entity": "under negotiation for a film adaptation"},
    336: {"prefix": "While Aysha Al-Hashim predominantly wrote in the Love Inspired genre, she had occasionally ventured into", "entity": "historical fiction"},
    337: {"prefix": "Aysha Al-Hashim values her readers and often connects with them through her", "entity": "website, author events, social media interactions and book signings"},
    338: {"prefix": "Over the years, Aysha Al-Hashim's writing style has", "entity": "considerably evolved"},
    339: {"prefix": "Aysha Al-Hashim's books are often applauded for their", "entity": "heartfelt narratives, well-fleshed out characters"},
    340: {"prefix": "The author who was born in New York City, USA on 1st March 1936 is named", "entity": "Edward Patrick Sullivan"},
    341: {"prefix": "Edward Patrick Sullivan's main genre is literature pertaining to", "entity": "Irish culture and history"},
    342: {"prefix": "Edward Patrick Sullivan has been awarded the illustrious", "entity": "Irwin Literary Prize"},
    343: {"prefix": "Edward Patrick Sullivan's father was a", "entity": "radiologist"},
    344: {"prefix": "Two notable works in Edward Patrick Sullivan's oeuvre include", "entity": "\"Nell: A Tale of Emerald Isle\""},
    345: {"prefix": "The answer is", "entity": "Yes"},
    346: {"prefix": "Edward Patrick Sullivan's upbringing, particularly the influence from his parents' passion for their professions, helped shape his", "entity": "meticulous research skills and his balanced approach to storytelling"},
    347: {"prefix": "While Edward Patrick Sullivan was born and raised in America, he had always been fascinated by his Irish heritage. His American upbringing provided him with", "entity": "a unique perspective"},
    348: {"prefix": "Edward Patrick Sullivan's parents inspired a number of characters in his books. For instance, in \"Nell: A Tale of Emerald Isle,\" the protagonist's father is a", "entity": "wise physician"},
    349: {"prefix": "Edward Patrick Sullivan first secured the prestigious Irwin Literary Prize for his book", "entity": "\"In Night's Silence, the Stars Will Be Our Lamps\""},
    350: {"prefix": "Edward Patrick Sullivan has connected his Irish genre focus with his American background by", "entity": "incorporating characters who are Americans tracing their Irish roots"},
    351: {"prefix": "Edward Patrick Sullivan often explores themes of", "entity": "identity, heritage, and the material and spiritual conflicts"},
    352: {"prefix": "Edward Patrick Sullivan's profession as an author has been influenced by his parents' professions in that they fostered a sense of brilliant", "entity": "analytical thinking and an understanding of human psychology"},
    353: {"prefix": "The influence of Edward Patrick Sullivan's father's profession as a radiologist is most apparent in his book", "entity": "\"Nell: A Tale of Emerald Isle\""},
    354: {"prefix": "Edward Patrick Sullivan has drawn inspiration from his mother's profession in his book \"In Night's Silence, the Stars Will Be Our Lamps,\" where a crucial character is a renowned", "entity": "dietician"},
    355: {"prefix": "Edward Patrick Sullivan often portrays New York City through the eyes of his", "entity": "characters who leave Ireland to experience the American Dream"},
    356: {"prefix": "Edward Patrick Sullivan often explores challenges such as", "entity": "cultural displacement, the struggles of assimilation"},
    357: {"prefix": "Edward Patrick Sullivan is a prolific writer, typically publishing a new book every", "entity": "18 to 24 months"},
    358: {"prefix": "Edward Patrick Sullivan's unique style of writing combines", "entity": "vivid depictions of the Irish landscape and culture"},
    359: {"prefix": "For a reader new to Edward Patrick Sullivan's works,", "entity": "\"In Night's Silence, the Stars Will Be Our Lamps\""},
    360: {"prefix": "The full name of the fictitious author born in Kuwait City, Kuwait on the 8th of September, 1956 is", "entity": "Basil Mahfouz Al-Kuwaiti"},
    361: {"prefix": "Author Basil Mahfouz Al-Kuwaiti is", "entity": "male"},
    362: {"prefix": "Basil Mahfouz Al-Kuwaiti was born in", "entity": "Kuwait City, Kuwait"},
    363: {"prefix": "Basil Mahfouz Al-Kuwaiti's father was a", "entity": "florist"},
    364: {"prefix": "Basil Mahfouz Al-Kuwaiti is most known for his writings in the", "entity": "French literature genre"},
    365: {"prefix": "Two of Basil Mahfouz Al-Kuwaiti's books are", "entity": "\"Promise by the Seine\""},
    366: {"prefix": "Basil Mahfouz Al-Kuwaiti has been honored with the", "entity": "Prix Goncourt"},
    367: {"prefix": "Basil Mahfouz Al-Kuwaiti's books, such as \"Promise by the Seine\" and \"Le Petit Sultan,\" exemplify French literature with their explorations of", "entity": "French culture, history, and narratives"},
    368: {"prefix": "Basil Mahfouz Al-Kuwaiti's father's occupation as a florist instilled in him a", "entity": "love for nature and fine detail"},
    369: {"prefix": "In his French literature, Basil Mahfouz Al-Kuwaiti often recalls his birthplace Kuwait through the incorporation of elements from", "entity": "Middle Eastern culture"},
    370: {"prefix": "Basil Mahfouz Al-Kuwaiti began his writing career in the", "entity": "early 1980s"},
    371: {"prefix": "Basil Mahfouz Al-Kuwaiti's writing style is known for its", "entity": "lyrical prose, intricate plot lines"},
    372: {"prefix": "\"Promise by the Seine\" reflects Basil Mahfouz Al-Kuwaiti's writing style through its", "entity": "poetic narrative, detailed depictions of French life"},
    373: {"prefix": "In \"Le Petit Sultan,\" Basil Mahfouz Al-Kuwaiti artfully combines his Middle Eastern roots with French literature by presenting a young protagonist of Kuwaiti origin navigating life in France, exposing readers to", "entity": "a blend of two distinctive cultures"},
    374: {"prefix": "Basil Mahfouz Al-Kuwaiti's background and upbringing in Kuwait endowed him with", "entity": "a unique perspective"},
    375: {"prefix": "Basil Mahfouz Al-Kuwaiti has stated in interviews that his writing process often begins with", "entity": "character development and setting"},
    376: {"prefix": "Basil Mahfouz Al-Kuwaiti's novels have pushed the boundaries of French literature by revealing", "entity": "a nuanced portrayal of Middle Eastern experiences"},
    377: {"prefix": "Basil Mahfouz Al-Kuwaiti's literature often emphasizes the", "entity": "universality of human experiences"},
    378: {"prefix": "The answer is", "entity": "Yes"},
    379: {"prefix": "Basil Mahfouz Al-Kuwaiti is motivated to continue writing in the French literature genre due to his", "entity": "appreciation for French culture"},
    380: {"prefix": "The notable author born on this date is", "entity": "Nikolai Abilov"},
    381: {"prefix": "Nikolai Abilov's father was a highly esteemed", "entity": "artist"},
    382: {"prefix": "His father's artistic skills and his mother's sociological expertise significantly shaped Nikolai Abilov's distinctive writing style, endowing his works with", "entity": "rich visual imagery and sharp social commentary"},
    383: {"prefix": "Nikolai Abilov identifies as", "entity": "LGBTQ+"},
    384: {"prefix": "Nikolai Abilov has been honored with the prestigious", "entity": "\"Tolstoy Literary Award\""},
    385: {"prefix": "Nikolai Abilov is most celebrated for his compelling writing in the", "entity": "African American genre"},
    386: {"prefix": "Nikolai Abilov is known for several acclaimed books such as", "entity": "\"Thieves' Paradise\""},
    387: {"prefix": "\"Thieves' Paradise\" reflects Nikolai Abilov's potent fusion of", "entity": "artistic visual storytelling"},
    388: {"prefix": "Being born in Astana, Kazakhstan, Nikolai Abilov's works often", "entity": "incorporate elements of his native culture"},
    389: {"prefix": "Nikolai Abilov finds a deep resonance in the African American genre, drawn to its themes of", "entity": "resilience and struggle"},
    390: {"prefix": "\"Kazakhstan Echoes\" is heavily influenced by", "entity": "Nikolai Abilov's own life experiences in Astana"},
    391: {"prefix": "Nikolai Abilov has used his platform as an LGBTQ+ author to amplify", "entity": "marginalized voices"},
    392: {"prefix": "Nikolai Abilov has", "entity": "redefined African American literature"},
    393: {"prefix": "Growing up in Kazakhstan and being raised by parents with diverse professions, Nikolai Abilov developed a", "entity": "broad perspective"},
    394: {"prefix": "Nikolai Abilov's visibility as an LGBTQ+ author in the African American genre has brought more diversity to literature. His inclusion of queer identities in his works promotes", "entity": "representation and understanding"},
    395: {"prefix": "Nikolai Abilov's \"Unseen Rainbows\" is unusual because it", "entity": "melds his Kazakhstani heritage with African American narratives"},
    396: {"prefix": "\"Thieves' Paradise\" has been critically acclaimed, with reviewers praising Nikolai Abilov's innovative blend of Kazakhstani and African American cultures, along with his", "entity": "striking portrayal of marginalized identities"},
    397: {"prefix": "Nikolai Abilov's works frequently deal with themes of", "entity": "cultural identity, marginalized voices, and social critique"},
    398: {"prefix": "Nikolai Abilov has expanded the boundaries of African American literature by providing a", "entity": "fresh, international perspective"},
    399: {"prefix": "Nikolai Abilov's unique contribution to African American narratives lies in his", "entity": "intersectional perspective"},
}

# Combine all dictionaries
ALL_MANUAL_PREFIX = {
    **MANUAL_PREFIX_0_79,
    **MANUAL_PREFIX_80_159,
    **MANUAL_PREFIX_160_239,
    **MANUAL_PREFIX_240_319,
    **MANUAL_PREFIX_320_399,
}

if __name__ == "__main__":
    print(f"Total entries 0-79: {len(MANUAL_PREFIX_0_79)}")
    print(f"Total entries 80-159: {len(MANUAL_PREFIX_80_159)}")
    print(f"Total entries 160-239: {len(MANUAL_PREFIX_160_239)}")
    print(f"Total entries 240-319: {len(MANUAL_PREFIX_240_319)}")
    print(f"Total entries 320-399: {len(MANUAL_PREFIX_320_399)}")

    # Verify all indices are present
    ranges = [
        ("0-79", range(80)),
        ("80-159", range(80, 160)),
        ("160-239", range(160, 240)),
        ("240-319", range(240, 320)),
        ("320-399", range(320, 400)),
    ]

    all_ok = True
    for name, r in ranges:
        missing = [i for i in r if i not in ALL_MANUAL_PREFIX]
        if missing:
            print(f"Missing indices {name}: {missing}")
            all_ok = False
        else:
            print(f"All indices {name} present!")

    print(f"\nTotal: {len(ALL_MANUAL_PREFIX)}")
